# Generated by Django 3.1.1 on 2020-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='name',
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_ad',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_biyografi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_dogum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_dogum_yeri',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_imdb_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_pp_linki',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='yonetmen_tmdb_id',
            field=models.TextField(default=''),
        ),
    ]
