# Generated by Django 3.1.1 on 2020-10-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_likedmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovies',
            name='movies',
            field=models.TextField(default=''),
        ),
    ]
